Dao3
AntonPanchishko/ApplicationHW pull request #4
Opened 2021-01-12 14:58 UTC by AntonPanchishko

2021-01-12 15:16 UTC, vicire requested changes
There are some remarks. Also you need to add yml file for Travis check

2021-01-12 15:16 UTC, vicire commented on src/main/java/taxi/dao/ManufacturerDaoImpl.java
> +        return Storage.manufacturers.set((int) manufacturer.getId(), manufacturer);
```suggestion
        return Storage.manufacturers.set(Storage.manufacturers.indexOf(manufacturer), manufacturer);
```

2021-01-12 15:16 UTC, vicire commented on src/main/java/taxi/dao/ManufacturerDaoImpl.java
> +        return false;
you need to write implementation

2021-01-12 15:16 UTC, vicire commented on src/main/java/taxi/model/Manufacturer.java
> +public class Manufacturer {
you made misprint - Manufacturer class has such field as id, name and country

2021-01-12 15:16 UTC, vicire commented on src/main/java/taxi/model/Car.java
> +    public Car(String model, Manufacturer manufacturer, List<Driver> drivers) {
you don`t need to put drivers here

2021-01-12 16:29 UTC, vicire approved these changes

2021-01-12 16:29 UTC, vicire commented on .travis.yml
> +    - $HOME/.m2
you need to add newline in the end

2021-01-12 16:29 UTC, vicire commented on src/main/java/taxi/model/Manufacturer.java
> +    public long getId() {
need to use Wrapper

2021-01-12 16:29 UTC, vicire commented on src/main/java/taxi/model/Driver.java
> +    public long getId() {
need to use Wrapper

2021-01-13 08:46 UTC, Sofasmile requested changes

2021-01-13 08:46 UTC, Sofasmile commented on pom.xml
>  </project>
let's add an empty line at the end of the file

2021-01-13 08:46 UTC, Sofasmile commented on src/main/java/taxi/dao/ManufacturerDaoImpl.java
> +        return Optional.of(Storage.manufacturers.get(Math.toIntExact(id)));
чи завжди ід буде відповідати позиції елементів в списку? Що якщо ми видалимо пару елементів з середини списку?

2021-01-13 08:46 UTC, Sofasmile commented on src/main/java/taxi/dao/ManufacturerDaoImpl.java
> +                .set(Storage.manufacturers.indexOf(manufacturer), manufacturer);
у випадку якщо такого manufacturer не знайдено, метод indexOf поверне -1 і в нас виникне IndexOutOfBoundException

2021-01-13 08:46 UTC, Sofasmile commented on src/main/java/taxi/model/Car.java
> +    private long id;
https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/03_dao_service_checklist.html

> Use wrapper for id: Long id but not long id. And remember what is the difference between == and equals.

2021-01-13 08:46 UTC, Sofasmile commented on src/main/java/taxi/model/Car.java
> +        this.manufacturer = manufacturer;
давай створимо пустий список драйверів в конструкторі

2021-01-13 09:20 UTC, Sofasmile approved these changes
можна мержити і приступати до наступної дз)

2021-01-13 09:20 UTC, Sofasmile commented on src/main/java/taxi/dao/ManufacturerDaoImpl.java
> +                .filter(e -> Objects.equals(e.getId(), id)).findFirst();
```suggestion
                .filter(e -> Objects.equals(e.getId(), id))
                .findFirst();
```

2021-01-13 09:45 UTC, merged