7) added Services for Car and Driver
AntonPanchishko/ApplicationHW pull request #5
Opened 2021-01-13 11:48 UTC by AntonPanchishko

2021-01-13 11:56 UTC, Max-Pochepets requested changes

2021-01-13 11:56 UTC, Max-Pochepets commented on src/main/java/taxi/dao/CarDao.java
> +    void removeDriverFromCar(Driver driver, Car car);
these methods shouldn't be in DAO layer

2021-01-13 12:46 UTC, Max-Pochepets requested changes

2021-01-13 12:46 UTC, Max-Pochepets commented on src/main/java/taxi/service/CarServiceImpl.java
> +        Storage.cars.stream()
you shouldn't access DB from Service. Use DAO

2021-01-13 12:46 UTC, Max-Pochepets commented on src/main/java/taxi/service/CarServiceImpl.java
> +            for (int j = 0; j < Storage.cars.get(j).getDrivers().size(); j++) {
same

2021-01-13 13:30 UTC, Max-Pochepets approved these changes

2021-01-13 13:35 UTC, RomanDubovskyi requested changes

2021-01-13 13:35 UTC, RomanDubovskyi commented on src/main/java/taxi/dao/CarDao.java
> +    Car get(Long id);
we return Optional on dao layer

2021-01-13 13:35 UTC, RomanDubovskyi commented on src/main/java/taxi/dao/CarDao.java
> +    void addDriverToCar(Driver driver, Car car);
checklist

2021-01-13 13:35 UTC, RomanDubovskyi commented on src/main/java/taxi/dao/CarDaoImpl.java
> +        Car oldCar = get(currentCarId);
```suggestion
        Car oldCar = get(car.getId());
```

2021-01-13 13:35 UTC, RomanDubovskyi commented on src/main/java/taxi/dao/DriverDaoImpl.java
> +    public Driver update(Driver driver) {
same here

2021-01-13 13:35 UTC, RomanDubovskyi commented on src/main/java/taxi/service/CarServiceImpl.java
> +        return carsByDriver;
let's move this logic to the dao layer, we should receive already filtered data from dao

2021-01-13 13:35 UTC, RomanDubovskyi commented on src/main/java/taxi/service/CarServiceImpl.java
> +                .removeIf(e -> Objects.equals(e, driver));
```suggestion
        car.getDrivers().remove(driver);
        carDao.update(car);
```

2021-01-13 14:17 UTC, RomanDubovskyi requested changes

2021-01-13 14:17 UTC, RomanDubovskyi commented on src/main/java/taxi/dao/CarDao.java
> +    void addDriverToCar(Driver driver, Car car);
what about this comment?

2021-01-14 08:37 UTC, RomanDubovskyi approved these changes
fix comments before merging this PR

2021-01-14 08:37 UTC, RomanDubovskyi commented on src/main/java/taxi/dao/CarDaoImpl.java
> +        return get(currentCarId).get();
```suggestion
        Car oldCar = get(car.getId()).get();
        Storage.cars.set(Storage.cars.indexOf(oldCar), car);
        return get(car.getId).get();
```

2021-01-14 08:37 UTC, RomanDubovskyi commented on src/main/java/taxi/dao/DriverDaoImpl.java
> +        Long currentDriverId = driver.getId();
```suggestion
```

2021-01-14 09:02 UTC, merged