18) added DriverDaoJdbcImpl, CarDaoJdbcImpl
AntonPanchishko/ApplicationHW pull request #7
Opened 2021-01-18 17:58 UTC by AntonPanchishko

2021-01-18 18:43 UTC, vicire requested changes

2021-01-18 18:43 UTC, vicire commented on src/main/java/taxi/dao/jdbc/CarDaoJdbcImpl.java
> +            throw new DataProcessingException("Couldn't add car into DB ", ex);
```suggestion
            throw new DataProcessingException("Couldn't add car " + car + " into DB ", ex);
```

2021-01-18 18:43 UTC, vicire commented on src/main/java/taxi/dao/jdbc/CarDaoJdbcImpl.java
> +            return Optional.of(car);
What happened if a car will be empty?

2021-01-18 18:43 UTC, vicire commented on src/main/java/taxi/dao/jdbc/CarDaoJdbcImpl.java
> +        Manufacturer manufacturer = ManufacturerDaoJdbcImpl.createManufacturerFromDb(resultSet);
that`s optional but I think that using ManufacturerDaoJdbcImpl is not a good idea. Better to make a separate method here.

2021-01-18 18:43 UTC, vicire commented on src/main/java/taxi/dao/jdbc/CarDaoJdbcImpl.java
> +        deleteObjectInCarDriverById(car.getId());
You open one more connection here and under

2021-01-18 18:43 UTC, vicire commented on src/main/java/taxi/dao/jdbc/CarDaoJdbcImpl.java
> +    private boolean insertNewDateInCarDriver(Long driverId, Long carId) {
you can make this method void

2021-01-18 18:43 UTC, vicire commented on src/main/java/taxi/dao/jdbc/CarDaoJdbcImpl.java
> +    private boolean deleteObjectInCarDriverById(Long id) {
Same here

2021-01-18 18:43 UTC, vicire commented on src/main/java/taxi/dao/jdbc/DriverDaoJdbcImpl.java
> +            throw new DataProcessingException("Couldn't add driver into DB ", ex);
Same as in create method in carDao

2021-01-18 18:43 UTC, vicire commented on src/main/java/taxi/dao/jdbc/ManufacturerDaoJdbcImpl.java
> +    public static Manufacturer createManufacturerFromDb(ResultSet resultSet) throws SQLException {
not a good practice, coz now all user can use this method in other classes

2021-01-18 19:53 UTC, vicire approved these changes

2021-01-19 11:11 UTC, dmytro-hryhoruk requested changes

2021-01-19 11:11 UTC, dmytro-hryhoruk commented on src/main/java/taxi/dao/jdbc/CarDaoJdbcImpl.java
> +        return car;
let's use one connection for each insert and not create the new one on each iteration

2021-01-19 11:11 UTC, dmytro-hryhoruk commented on src/main/java/taxi/dao/jdbc/CarDaoJdbcImpl.java
> +                + "WHERE d.driver_id = ? AND deleted = false ";
this deleted = false works for both car and driver? Let's better specify the table name and write this condition twice for car and for dirver

2021-01-19 16:16 UTC, dmytro-hryhoruk approved these changes

2021-01-19 19:44 UTC, merged