Branch for hw dao7
AntonPanchishko/ApplicationHW pull request #8
Opened 2021-01-19 19:56 UTC by AntonPanchishko

2021-01-19 20:35 UTC, vicire requested changes
nice, I have only some little remarks :)

2021-01-19 20:35 UTC, vicire commented on src/main/java/taxi/dao/ManufacturerDao.java
> +public interface ManufacturerDao extends GenericDao<Manufacturer, Long> {
You can delete all methods under, that you declared in GenericDao. Same in other Dao and Service

2021-01-19 20:35 UTC, vicire commented on src/main/webapp/WEB-INF/views/index.jsp
> +</html>
add the empty line in the end

2021-01-19 20:35 UTC, vicire commented on src/main/webapp/web.xml
> +</web-app>
add empty line here

2021-01-19 20:54 UTC, vicire approved these changes

2021-01-20 07:12 UTC, boroda4436 requested changes
https://mate-academy.github.io/jv-program-fulltime/02_jdbc/checklist/07_servlets_intro_checklist.html

2021-01-20 09:52 UTC, boroda4436 approved these changes

2021-01-20 10:00 UTC, merged